using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PoolManager : MonoBehaviour
{
    //1. 프리팹들을 보관할 변수
    public GameObject[] prefabs;
    public GameObject[] subPrefabs;//for gameobjects generated by bullets, such as slowfield
    //2. 풀 담당을 하는 리스트들
    List<GameObject>[] pools;
    List<GameObject>[] subpools;//for gameobjects generated by bullets, such as slowfield

    void Awake(){
        pools = new List<GameObject>[prefabs.Length];

        for(int i = 0; i < prefabs.Length; i++){
            pools[i] = new List<GameObject>();
        }

        subpools = new List<GameObject>[subPrefabs.Length];
        
        for(int i = 0; i < subPrefabs.Length; i++){
            subpools[i] = new List<GameObject>();
        }

    }

    public GameObject Get(int index){
        GameObject select = null;

        //선택한 풀의 놀고있는 오브젝트 접근
        foreach(GameObject obj in pools[index]){
            if(!obj.activeSelf){
                select = obj;
                select.SetActive(true);
                break;
            }
        }
        //없으면 새로 생성해서 pool에 추가 후 가져가기
        if(!select){
            select = Instantiate(prefabs[index], transform);
            pools[index].Add(select);
        }
        return select;
    }

    public GameObject GetSub(int index){
        GameObject select = null;

        //선택한 풀의 놀고있는 오브젝트 접근
        foreach(GameObject obj in subpools[index]){
            if(!obj.activeSelf){
                select = obj;
                select.SetActive(true);
                break;
            }
        }
        //없으면 새로 생성해서 pool에 추가 후 가져가기
        if(!select){
            select = Instantiate(subPrefabs[index], transform);
            subpools[index].Add(select);
        }
        return select;
    }

}
